export const productsData = [
  {
    id: 1,
    name: 'Laptop',
    category: 'Electronics',
    price: 799.99,
    description: 'Powerful laptop with a high-resolution display.',
    image: 'laptop.jpg',
  },
  {
    id: 2,
    name: 'Running Shoes',
    category: 'Footwear',
    price: 99.99,
    description: 'Comfortable running shoes for your active lifestyle.',
    image: 'shoes.jpg',
  },
  {
    id: 3,
    name: 'Coffee Maker',
    category: 'Appliances',
    price: 49.99,
    description: 'Brew your favorite coffee with this easy-to-use coffee maker.',
    image: 'coffee_maker.jpg',
  },
  {
    id: 4,
    name: 'T-shirt',
    category: 'Clothing',
    price: 19.99,
    description: 'Casual and stylish t-shirt for everyday wear.',
    image: 'tshirt.jpg',
  },
  {
    id: 5,
    name: 'Smartphone',
    category: 'Electronics',
    price: 499.99,
    description: 'The latest smartphone with advanced features.',
    image: 'smartphone.jpg',
  },
  {
    id: 6,
    name: 'Kitchen Mixer',
    category: 'Appliances',
    price: 149.99,
    description: 'Effortlessly mix ingredients for your baking needs.',
    image: 'mixer.jpg',
  },
  {
    id: 7,
    name: 'Backpack',
    category: 'Travel',
    price: 39.99,
    description: 'Stylish and spacious backpack for your adventures.',
    image: 'backpack.jpg',
  },
  {
    id: 8,
    name: 'Sunglasses',
    category: 'Accessories',
    price: 29.99,
    description: 'Fashionable sunglasses to protect your eyes in style.',
    image: 'sunglasses.jpg',
  },
  {
    id: 9,
    name: 'Yoga Mat',
    category: 'Fitness',
    price: 24.99,
    description: 'Non-slip yoga mat for your daily workouts.',
    image: 'yoga_mat.jpg',
  },
  {
    id: 10,
    name: 'Gaming Console',
    category: 'Electronics',
    price: 299.99,
    description: 'Next-gen gaming console for immersive gaming experiences.',
    image: 'gaming_console.jpg',
  },
  {
    id: 11,
    name: 'Desk Chair',
    category: 'Furniture',
    price: 129.99,
    description: 'Ergonomic desk chair for comfortable work or gaming.',
    image: 'desk_chair.jpg',
  },
  {
    id: 12,
    name: 'Smart Watch',
    category: 'Electronics',
    price: 79.99,
    description: 'Stay connected and track your fitness with a smartwatch.',
    image: 'smart_watch.jpg',
  },
  {
    id: 13,
    name: 'Dress Shoes',
    category: 'Footwear',
    price: 59.99,
    description: 'Classic dress shoes for formal occasions.',
    image: 'dress_shoes.jpg',
  },
  {
    id: 14,
    name: 'Camera',
    category: 'Electronics',
    price: 399.99,
    description: 'Capture memories with a high-quality digital camera.',
    image: 'camera.jpg',
  },
  {
    id: 15,
    name: 'Headphones',
    category: 'Electronics',
    price: 49.99,
    description: 'Immerse yourself in music with premium headphones.',
    image: 'headphones.jpg',
  },
];
